spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

springfox:
  documentation:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: debug