server:
  port: 8721

spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider
          uri: lb://provider
          predicates:
            - Path=/provider/**
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**

  main:
    web-application-type: reactive

exclude:
  path: /v2/api-docs,/swagger**/**,/webjars/**,/v2/**,/swagger-ui.html,/doc.html,/error

logging:
  level:
    org.springframework.cloud.gateway: debug

