spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.123:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.253.123:8848
        username: nacos
        password: nacos
        file-extension: yaml
springfox:
  documentation:
    enabled: true
