spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.123:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.253.123:8848
        username: nacos
        password: nacos
        file-extension: yaml
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
springfox:
  documentation:
    enabled: true