server:
  port: 8212
spring:
  profiles:
    active: dev
  application:
    name: provider
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
    health:
      show-details: always